export const REPOSITORIES = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  TASK_REPOSITORY: 'TASK_REPOSITORY',
  KANBAN_REPOSITORY: 'KANBAN_REPOSITORY',
  SHARED_KANBAN_REPOSITORY: 'SHARED-KANBAN_REPOSITORY'
};